### ISSUE TITLE
Create section Current Project/Docs

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#370]
This is just a proposal, @DFriend01 what do you think?

### Purpose

Documentation for this repository

### Page Tree

```yml
nav:
  ...
  - Current Project:
    ...
    - Docs:
      - Overview: current/docs/overview.md
      - Overview: current/docs/<tbd>.md
```

### Topics

I think we should structure it similar to the Sailbot Workspace section
- Overview page / README
    -  Mention that it is a part of sailbot workspace
    - CI defined in this repository: markdown-link-check, automated versioning
    - Mention mkdocs and link to markdown documentation
    - Point to second page?
- Second page: setup/run/workflow?
    - Link to "how to run optional software" in sailbot workspace section
    - Migrate what is currently in README to here

Or maybe we can fit this all into the README

### Resources

- https://patrick-5546.github.io/sampleproject/main/developer_guide/docs/#versioning
