### ISSUE TITLE
Create docs page Reference/Infrastructure/Docker

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/sailbot_workspace#372]
### Purpose

We use Docker for our workspace. Although we abstract most of Docker away from the software members, infrastructure members should have an understanding of how Docker works and how to use it so that they can make contributions to developing the workspace.

### Page Tree

```yml
nav:
  ...
  - Reference:
    - Infrastructure:
      - Docker: reference/infrastructure/docker.md
  ...
```

### Topics

- What is Docker and why do we use it?
- Describe the containerization process (Dockerfile &rarr; Image &rarr; Container)
  - Provide a small example of this process (could also just point to an example in the Docker docs)
- How do we use Docker for Sailbot (sailbot_workspace)
- Learning Resources for Docker

### Resources

- [Docker Overview](https://docs.docker.com/get-started/overview/)
