### ISSUE TITLE
Create docs page About Us

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#373]
### Purpose
Provide insight onto how our team is organized

### Page Tree
```yml
nav:
  ...
  - About Us: about.md
```

### Topics
- Software subteam descriptions

### Resources
- https://docs.google.com/document/d/1bToOV3JvMZFJ9jotrjlFIvDgY8xiXfH7Yg1wkGm8Qf4/edit
