### ISSUE TITLE
Create docs page Reference/Web Development

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#378]
### Purpose

Technical reference for website members

### Page Tree

```yml
nav:
  ...
  - Reference:
    ...
    - Web Development: reference/webdev.md
```

### Topics

- React
- Typescript
- Mongodb

### Resources

-
