### ISSUE TITLE
Create docs page Sailbot Workspace/Debugging

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#385]
### Page Tree
```yml
nav:
  ...
  - Sailbot Workspace:
    ...
    - Debugging: workspace/debugging.md
```

### Topics
- Result of https://github.com/UBCSailbot/sailbot_workspace/issues/6
